# Generated by Django 5.2 on 2025-04-12 14:17

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_user_alter_expense_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(default=core.models.get_default_currency, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.ForeignKey(default=core.models.get_default_currency, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='core.currency'),
        ),
    ]
