# Generated by Django 5.2 on 2025-04-12 18:06

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_expense_category_alter_income_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(default=core.models.get_default_currency, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='core.category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.ForeignKey(default=core.models.get_default_currency, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='core.currency'),
        ),
    ]
